version: '3.7'

services:
  frontend:
    image: krafthandel/starter-front
    build: frontend
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    image: krafthandel/starter-back
    build: backend
